application: london-teatime3
version: 1-0
runtime: python
api_version: 1

handlers:
    
- url: /public/favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /css
  static_dir: css

- url: /static
  static_dir: static
    
- url: /.*
  script: handlers.py
  login: required
